### PR TITLE
export ToasterProps type

### PR DESCRIPTION
**Pull request by Sam-Apostel**
For Sonner to be bundled in other libraries, we need to export `ToasterProps`.

This fixes following error for library authors:
```
TS4023: Exported variable 'X' has or is using name 'ToasterProps' from external module './node_modules/sonner/dist/index' but cannot be named
```

### Issue:

Closes https://github.com/emilkowalski/sonner/issues/399

### What has been done:

- exported `ToasterProps` from index

### CODE REVIEW

**Comment by omridevk** [comment]
@Sam-Apostel 
Can you also export all from here:
https://github.com/emilkowalski/sonner/blob/main/src/types.ts

I am getting a similar issue just with:

```
Exported variable 'toast' has or is using name 'ToastClassnames' from external module "/node_modules/sonner/dist/index" but cannot be named.
```

**Comment by hailwood** [comment]
I was just coming to the repo to ask for this.
For me it's `ToastIcons` that I was after.

**Comment by basickarl** [comment]
This should probably get merged.

**Comment by omridevk** [comment]
@emilkowalski  this does not include export to `ToastClassNames` I am still experiencing TS error.  
Should I make a PR adding export to that as well? 
Thanks

**Pull request merged**
