### PR TITLE
Warning and Info toasts

### PR DESCRIPTION
**Pull request by emreakdas**
#184 Warning and Info toasts add.

Light: 
image
image

Dark:
image
image

### CODE REVIEW

**Comment by emilkowalski** [comment]
Looks great! Can we remove the examples from the homepage tho? I want to prevent the horizontal overflow.

**Comment by emreakdas** [comment]
Thank you @emilkowalski  :) 

Should it be like this to prevent horizontal overflow or should I remove the instances?

image

**Comment by emilkowalski** [comment]
@emreakdas Let's do it like on the screenshot you posted.

**Comment by emreakdas** [comment]
@emilkowalski I added.

**Comment by emilkowalski** [comment]
Amazing, thank you so much!

**Pull request merged**
