### PR TITLE
types: change label types to ReactNode

### PR DESCRIPTION
**Pull request by CanRau**
Just started using sonner and realized `action.label` & `cancel.label` could accept `ReactNode` instead of `string` so you can pass in a more complex custom label including an icon or whatever.

Hope you agree, if not I'd be curious of possible downsides I might not've considered and can be closed.

Closes: #273

Also just saw that `cancel.onClick` is typed `onClick?: () => void;` while `action.onclick` = `onClick: (event: React.MouseEvent<HTMLButtonElement>) => void;` is there a reason or should I open another PR to add the event to `cancel.onClick` as well?

### CODE REVIEW

**Comment by emilkowalski** [comment]
> Just started using sonner and realized `action.label` & `cancel.label` could accept `ReactNode` instead of `string` so you can pass in a more complex custom label including an icon or whatever.
> 
> Hope you agree, if not I'd be curious of possible downsides I might not've considered and can be closed.
> 
> Closes: #273
> 
> Also just saw that `cancel.onClick` is typed `onClick?: () => void;` while `action.onclick` = `onClick: (event: React.MouseEvent<HTMLButtonElement>) => void;` is there a reason or should I open another PR to add the event to `cancel.onClick` as well?

Thank you! You can change the onClick types in this PR if you want to!

**Comment by emilkowalski** [comment]
Hmm... looks like there is a build error
CleanShot 2023-12-30 at 00 36 38@2x

**Comment by CanRau** [comment]
I think this might be fixed now after I actually passed the `event` to `cancel.onClick` ?

**Comment by emilkowalski** [comment]
Got some TS errors 
CleanShot 2023-12-30 at 00 51 40@2x

**Comment by CanRau** [comment]
😳 oops I'm sorry, should be fixed now, forgot to add the argument to the button's event handler, that happens when making PRs on GitHub 😅

**Pull request merged**
