### PR TITLE
Implement option to pause when document is hidden

### PR DESCRIPTION
**Pull request by etcd**
### Issue 😱:

Closes https://github.com/emilkowalski/sonner/issues/303

### What has been done ✅:

- Create `useIsDocumentHidden` hook
- Add `pauseWhenDocumentHidden` prop to `Toast` and `Toaster`
- Add logic to pause `Toast` timers when document is hidden
- Document prop for `Toaster`

### Screenshots/Videos 🎥:

N/A

### CODE REVIEW

**Comment by emilkowalski** [comment]
This is great! Could you perhaps clarify for the users what a hidden document is in the docs?

**Comment by etcd** [comment]
> This is great! Could you perhaps clarify for the users what a hidden document is in the docs?

Sure thing, just updated it with examples that come from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState).

**Comment by etcd** [comment]
@emilkowalski wdyt of this option being enabled by default? It would change the default behavior, but it also seems slightly more bug fix than feature in some sense, because I think most people would prefer for toasts to not silently appear+disappear when in the background. Up to you though!

**Comment by emilkowalski** [comment]
> @emilkowalski wdyt of this option being enabled by default? It would change the default behavior, but it also seems slightly more bug fix than feature in some sense, because I think most people would prefer for toasts to not silently appear+disappear when in the background. Up to you though!

Great call, let's make it the default.

**Comment by emilkowalski** [comment]
I'll merge for now as i want to release a new version, we can make it the default in the next PR.

**Pull request merged**
