### PR TITLE
chore: add threshold to start swipe

### PR DESCRIPTION
**Pull request by joaom00**

### CODE REVIEW

**Comment by emilkowalski** [comment]
Could you help me understand what this PR is doing?

**Comment by joaom00** [comment]
Basically the user needs to move a certain amount of pixels (2px with mouse and 10px with touch) on the y-axis to start swiping the toast. To avoid this:

Before

https://github.com/emilkowalski/sonner/assets/48808846/48e4ae17-5d98-4b21-a16b-ff0e74548758

After

https://github.com/emilkowalski/sonner/assets/48808846/3c5c213e-6171-4091-a4a2-c7baf44ec4e2

**Comment by emilkowalski** [comment]
@joaom00 Seems like some tests are failing.

**Comment by joaom00** [comment]
@emilkowalski Fixed

**Pull request merged**
