### PR TITLE
fix: turn section into live region #306

### PR DESCRIPTION
**Pull request by tricinel**
### Issue: Older screen readers don't announce individual toasts

`li` elements are not allowed to have the `role="status"` tag as per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#technical_summary).

Fixes https://github.com/emilkowalski/sonner/issues/306

### What has been done:

- [x] Removed `aria-live`, `aria-atomic` and `role` tags from the `<li>` element (the Toast)
- [x] Added `aria-live`, `aria-relevant` and `aria-atomic` to the containing `<section>` element
- [x] Removed the `important` key from the `ToastT` type

### Screenshots/Videos:

[N/A](https://github.com/emilkowalski/sonner/assets/216008/baace819-1ae9-4cbc-8fae-1913945af29d)

Visually, not changed. Tests all pass. Build passes.

#### Notes

This is be a breaking change because we remove the `important` key from the `ToastT` type, meaning that consumers will get a type error if they've been using the key so far. Happy to discuss another solution to this, if any.

### CODE REVIEW

**Comment by tricinel** [comment]
As a proposal, we could have a way to deprecate the `important` key in the `ToastT` interface. And maybe "announce" it for the next few minor versions. Meaning, we keep it but it does nothing so we can warn users that it will disappear and they have time to prepare.

**Review by rfoel — APPROVED** [review]

**Comment by tricinel** [comment]
Hm, I might need to update from main before it can be merged. I'll take care of that.

**Comment by andrewbarnesweb** [comment]
Is there any update on this PR? I could do with it as we have automated accessibility tests which it fails for... And for users 🙂

**Comment by tricinel** [comment]
I kept merging main into this, but I don't think it'll ever actually get merged, so I gave up :(

**Comment by tonyfarney** [comment]
Why do you think it will not be merged?

**Comment by tricinel** [comment]
There are plenty of PRs unmerged 🤷

**Comment by emilkowalski** [comment]
Thanks, merged. My guess is that not a lot of people use `important`, so it's ok to merge.

**Pull request merged**
