### PR TITLE
Get history of Toast

### LINKED ISSUE #176: How to get toast list?
How can I get a list of visible toasts?
Something like https://react-hot-toast.com/docs/use-toaster-store

### PR DESCRIPTION
**Pull request by dharanish-v**
toast.getHistory() will give the list the toast rendered

closes #176

### CODE REVIEW

**Comment by dharanish-v** [comment]
can we merge this? @emilkowalski

**Comment by emilkowalski** [comment]
Can we make it a hook that returns active toasts?

`const { toasts } = useSonner()`

**Comment by AlexanderChiclana** [comment]
Can this be merged? Id like to be able to block accidentally sending re-sending toasts which have an ID already in the toast history and don't know if there is another way to do this

**Comment by dharanish-v** [comment]
I am not currently working on this, feel to merge or close

**Pull request merged**
