### PR TITLE
HTML content sanitization and parsing for html tags inside toast

### PR DESCRIPTION
**Pull request by borisadamyan**
### Improvement:

Closes https://github.com/emilkowalski/sonner/issues/345

### What has been done ✅:
- 

- [  DOMPurify sanitize library added. ]
- [ Parsed value inserted into toast title and description to support HTML tags in toast. ]

### Screenshots/Videos 🎥:

N/A

### CODE REVIEW

**Review by NaveenkumarMD — APPROVED** [review]

**Comment by borisadamyan** [comment]
@emilkowalski 👋  Regarding the merging of dates in this fix, we need to use it in our project.  Could you please check why the deployment failed? Do we need to change anything else or is there some action needed to be done by you? Thanks

**Comment by borisadamyan** [comment]
@NaveenkumarMD Thank you for the review.

**Comment by emilkowalski** [comment]
@borisadamyan You have a frozen lock file

**Comment by borisadamyan** [comment]
> @borisadamyan You have a frozen lock file

OK, thanks for the note. Deployment passed successfully :)

**Comment by emilkowalski** [comment]
Thanks!

**Pull request merged**
