### PR TITLE
feat(Types): adds warning type toast

### PR DESCRIPTION
**Pull request by JayWelsh**
Adds a new toast type of "warning"

Screenshot 2023-03-14 at 11 27 54

I think it helps to differentiate between success, error and warning type toasts, and since I love this library and wanted to use a warning type, I thought I'd just add it here and create a PR in case you feel the same.

If you would prefer not to have a "warning" type toast, no problem.

Thanks!

### CODE REVIEW

**Comment by JayWelsh** [comment]
@emilkowalski have you by any chance had a chance to look at this? :)

**Comment by emilkowalski** [comment]
@JayWelsh This is awesome!

Could we change the colors to these? Also, I would love to swap the icon for the warning solid icon from https://heroicons.com/

Light:
background: `hsl(49, 100%, 96%)`
text: `hsl(22, 100%, 40%)`
border: `hsl(48, 100%, 88%)`

Dark:
background: `hsl(19, 86%, 8%)`
text: `hsl(48, 100%, 74%)`
border: `hsl(23, 100%, 14%)`,

**Comment by JayWelsh** [comment]
Thanks a lot @emilkowalski ! I've made the requested adjustments 👍

**Comment by fraserdale** [comment]
This looks great

**Comment by JayWelsh** [comment]
Hi @emilkowalski,

Is there anything I can do with this to make it more likely to be merged?

Kindes Regards,
Jay

**Comment by owieth** [comment]
> Hi @emilkowalski,
> 
> Is there anything I can do with this to make it more likely to be merged?
> 
> Kindest Regards, Jay

Try to merge the base branch into your branch:
This branch is out-of-date with the base branch

**Comment by JayWelsh** [comment]
> > Hi @emilkowalski,
> > Is there anything I can do with this to make it more likely to be merged?
> > Kindest Regards, Jay
> 
> Try to merge the base branch into your branch: This branch is out-of-date with the base branch

Done 👍

**Comment by emilkowalski** [comment]
After much consideration I decided to stick with the types we currently have. I appreciate your work a lot tho!

**Comment by JayWelsh** [comment]
Hmm, I know you're unlikely to change your mind but if you just Google image search "toast types web dev" pretty much every example shows an info type (default in the case of sonner), success, error, warning.

In my opinion, it's a strangely missing feature to have the warning type left out, and I think it would increase this library's adoption to have it. It's a totally standard type to have in a toast lib so I'm not sure why there's aversion.

But anyway just wanted to mention that, it's of course your choice.

**Pull request closed without merging**
