### PR TITLE
Allow passing a `Promise` to toast without wrapper function

### LINKED ISSUE #1: Allow passing `Promise` to `data.promise` instead of `() => Promise<any>`
First of all, great work, looks amazing and has a delightful user experience!!

One thing is, I would like to be able to use the toast like this:
```typescript

const promise = settingsMutation.mutate(...)

toast('Your settings have been updated', { promise })

```

Instead of writing it like this, since often times the mutation can have quite a bit of code inside, so wrapping it all with the toast feels unergonomic.
```typescript
toast('Your settings have been updated', { promise() {
  return settingsMutation.mutate(...)
}}
```

If you feel like this is a reasonable change, I would be glad to submit a Pull Request!

### PR DESCRIPTION
**Pull request by skoshx**
This commit makes it possible to pass promises straight to `toast.promise` as well as `data.promise`.

Some changes I had to make to get the development server working:
- Adding`postcss` as a dev dependency and adding `postcss.config.cjs` files as per https://tsup.egoist.dev/#css-support. 

Closes #1

### CODE REVIEW

**Comment by emilkowalski** [comment]
Thank you for the PR. 
What error did you get when you've tried running it locally? 
It's a pnpm project, so you'd do `pnpm i` and then `pnpm dev:website`, did you do that?

**Comment by skoshx** [comment]
These errors come up for me when just doing `git clone <sonner repo remote>`, then `pnpm install` followed by either `pnpm run dev` or `pnpm run dev:website`

This is the error im faced with on `localhost:3000`:

```typescript
./src/components/CodeBlock/code-block.module.css.webpack[javascript/auto]!=!../node_modules/.pnpm/next@13.1.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[5].use[2]!../node_modules/.pnpm/next@13.1.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[5].use[3]!./src/components/CodeBlock/code-block.module.css
TypeError: Cannot read properties of undefined (reading 'config')
```

This is the error from `dev` script (some logs omitted for brevity):

```typescript
 ✘ [ERROR] [plugin postcss] Cannot read properties of undefined (reading 'config')
sonner:dev: 
sonner:dev:     ../../node_modules/.pnpm/tailwindcss@3.2.7_postcss@8.4.21/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:85:62:
sonner:dev:       85 │ ...lveConfig.default)(configOrPath.config === undefined ? configOr...
sonner:dev:          ╵                                    ^
sonner:dev: 
sonner:dev:     at getTailwindConfig (/Users/rasmus/Desktop/DEV/Web/node_modules/.pnpm/tailwindcss@3.2.7_postcss@8.4.21/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:85:63)

This error came from the "onLoad" callback registered here:
sonner:dev: 
sonner:dev:     node_modules/.pnpm/tsup@6.5.0_typescript@4.9.4/node_modules/tsup/dist/index.js:1329:13:
sonner:dev:       1329 │       build2.onLoad({ filter: /\.css$/ }, async (args) => {
sonner:dev:            ╵        

 The plugin "postcss" was triggered by this import
sonner:dev: 
sonner:dev:     src/index.tsx:5:7:
sonner:dev:       5 │ import './styles.css';
sonner:dev:         ╵        ~~~~~~~~~~~~~~
```

**Comment by emilkowalski** [comment]
Which pnpm version are you using?

**Comment by skoshx** [comment]
`$ pnpm --version` 7.27.1

Actually I just reinstalled it last night, so I would assume it's up to date

**Comment by emilkowalski** [comment]
That's really weird, especially the tailwind part.
Is this the folder where you cloned it?
`Users/rasmus/Desktop/DEV/Web/node_modules/`

**Comment by skoshx** [comment]
Haha, now that you mentioned the `node_modules` being in that folder I got it fixed. I had some `node_modules` in the root and somehow it used that one...

Removed the postcss stuff now!

**Comment by emilkowalski** [comment]
Could you format your changes befor merging? I'll add prettier file soon to avoid this kind of problems. Sorry!

**Comment by skoshx** [comment]
Do you wanna paste your preferred prettier config here and I can just add it to this PR and use it to format aswell?

**Comment by emilkowalski** [comment]
I've just pushed a prettier config, you can rebase 👍🏻

**Comment by skoshx** [comment]
Good to go now? Added `format` script and `prettier` as devDependency

**Comment by emilkowalski** [comment]
Yes, thank you so much ❤️

**Pull request merged**
