### PR TITLE
allow user to use React elements also inside toaster

### PR DESCRIPTION
**Pull request by borisadamyan**
### Issue 😱:

Closes https://github.com/emilkowalski/sonner/issues/378

allow the user to use React elements within the toaster description section. ✅ 

### Screenshots/Videos 🎥:

Screenshot 2024-03-21 at 09 51 00
Screenshot 2024-03-21 at 09 54 50

### CODE REVIEW

**Comment by macalinao** [comment]
Looking forward to this getting merged.

**Comment by borisadamyan** [comment]
> Looking forward to this getting merged.
 Yeah. Let's wait for @emilkowalski to approve.

**Comment by jose-donato** [comment]
amazing!

looking forward to this one as well 👍

**Review by joaom00 — APPROVED** [review]

**Comment by peetzweg** [comment]
Whoops implemented this quickly as well. However, I also added some tests to prevent this happening again in the future. Maybe worthwhile bringing them in as well? https://github.com/emilkowalski/sonner/pull/387

**Comment by borisadamyan** [comment]
Just for reminder @emilkowalski

**Comment by borisadamyan** [comment]
> > Looking forward to this getting merged.
> 
>  Yeah. Let's wait for @emilkowalski to approve.

Just for reminder @emilkowalski

**Comment by emilkowalski** [comment]
Fixed in #387

**Comment by jose-donato** [comment]
> Fixed in #387

is a new version going to be released with this?

**Pull request closed without merging**
