### PR TITLE
bump packages

### PR DESCRIPTION
**Pull request by choeqq**
### Issue:
Closes https://github.com/emilkowalski/sonner/issues/282

### What has been done:
- updated packages 😄 
- run format command

### Screenshots / videos: 
Screenshot 2023-12-30 at 19 54 03

### CODE REVIEW

**Comment by choeqq** [comment]
I am not sure why deployment fails, build seems to go smoothly 🤔 
Screenshot 2023-12-30 at 20 01 38

**Comment by choeqq** [comment]
Updated playwright tests according to [release notes](https://playwright.dev/docs/release-notes#breaking-changes-playwright-no-longer-downloads-browsers-automatically), 
Screenshot 2023-12-31 at 18 11 12
Locally tests seem to be correct 🤔

**Comment by emilkowalski** [comment]
@choeqq Any updates here?

**Comment by choeqq** [comment]
hi @emilkowalski just updated playwright test issue, fingers crossed it will fix test bug 😬

**Comment by choeqq** [comment]
@emilkowalski all checks passed 🥳 
It would be nice to check and merge it ASAP, so there won't be too many conflicts 😉

**Pull request merged**
